name: Build frontend image
on:
  push:
    paths: ["frontend/**", ".github/workflows/build-frontend.yml"]
  pull_request:
    paths: ["frontend/**", ".github/workflows/build-frontend.yml"]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: local/ch-frontend:dev
