name: Build backend image
on:
  push:
    paths: ["backend/**", ".github/workflows/build-backend.yml"]
  pull_request:
    paths: ["backend/**", ".github/workflows/build-backend.yml"]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false # build only (no registry)
          tags: local/ch-backend:dev
