name: Trivy scan (Dockerfiles)
on:
  pull_request:
    paths:
      - "backend/**"
      - "frontend/**"
  workflow_dispatch: {}
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          scan-ref: "./backend"
          hide-progress: true
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: "fs"
          scan-ref: "./frontend"
          hide-progress: true
